### PR TITLE
bugfix: fix to the network interfaces loop

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
I have fixed a bug affecting the webinterfaces loop. The previous was using the 'this' context in the wrong way. The forEach method needs an array of arguments https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### CODE REVIEW

**Comment by WebReflection** [comment]
sorry but there was nothing wrong in passing the key and using it as `this` in that function … amI missing something? I don't see any improvement with your passed array

**Comment by WebReflection** [comment]
also .. the en1 was for the WiFi interface, not the network one, but I actually agree that could be handy sometimes but that is not an issue. Last, but not least, the change to the layout involves an external network request, something I really don't want to make when testardo runs behind SIM card based hot-spots (which is my case). So, the only thing I see as improvement is the et0 but then the RegExp would be en\d+ . I'll close this for now

**Comment by WebReflection** [comment]
pls check latest, thanks :-)

**Comment by GianlucaGuarini** [comment]
Ok thanks now it works again. I thought the problem was also into the forEach loop key param but it seems it was just the regex thank you again :+1:

**Pull request closed without merging**
